import express from "express";

import {
  getSummary,
  getRevenue,
  getProductPerformance,
  getCustomerDistribution,
  getRecentOrders,
  getActivity,
  getChurnAnalytics,
  getCLVAnalytics,
  getMarketBasketAnalytics,
  getRecommendationAnalytics,
  getForecastAnalytics,
} from "../controllers/dashboard.controller.js";

import {
  authenticate,
} from "../middleware/auth.middleware.js";

/* =========================================================
   ROUTER
========================================================= */

const router = express.Router();

/* =========================================================
   AUTHENTICATION

   Every route declared below this middleware is protected.

   Requests must contain a valid:
   auth_token cookie
========================================================= */

router.use(authenticate);

/* =========================================================
   DASHBOARD SUMMARY

   GET /api/dashboard/summary
========================================================= */

router.get(
  "/summary",
  getSummary
);

/* =========================================================
   REVENUE ANALYTICS

   GET /api/dashboard/revenue
========================================================= */

router.get(
  "/revenue",
  getRevenue
);

/* =========================================================
   PRODUCT PERFORMANCE

   GET /api/dashboard/products
========================================================= */

router.get(
  "/products",
  getProductPerformance
);

/* =========================================================
   RECENT ORDERS

   GET /api/dashboard/orders
========================================================= */

router.get(
  "/orders",
  getRecentOrders
);

/* =========================================================
   CUSTOMER DISTRIBUTION

   GET /api/dashboard/customer-distribution
========================================================= */

router.get(
  "/customer-distribution",
  getCustomerDistribution
);

/* =========================================================
   CHURN ANALYTICS

   GET /api/dashboard/churn
========================================================= */

router.get(
  "/churn",
  getChurnAnalytics
);

/* =========================================================
   CUSTOMER LIFETIME VALUE

   GET /api/dashboard/clv
========================================================= */

router.get(
  "/clv",
  getCLVAnalytics
);

/* =========================================================
   MARKET BASKET ANALYSIS

   GET /api/dashboard/market-basket

   Returns the latest persisted Market Basket Analysis
   generated by the Apriori algorithm.

   Response includes:

   - Algorithm
   - Model version
   - Transaction count
   - Unique products
   - Frequent itemsets
   - Association rules
   - Average confidence
   - Maximum lift
   - Strongest rule
   - Analysis date
========================================================= */

router.get(
  "/market-basket",
  getMarketBasketAnalytics
);

/* =========================================================
   RECENT DASHBOARD ACTIVITY

   GET /api/dashboard/activity
========================================================= */

router.get(
  "/activity",
  getActivity
);

router.get(
  "/recommendations",
  getRecommendationAnalytics
);

/* =========================================================
   SALES FORECAST

   GET /api/dashboard/forecasting

   Returns the latest persisted sales forecast generated
   by the forecasting model.
========================================================= */

router.get(
  "/forecasting",
  getForecastAnalytics
);

/* =========================================================
   EXPORT ROUTER
========================================================= */

export default router;